#!/bin/bash

# Get the path location of the executing script
## http://stackoverflow.com/questions/630372/determine-the-path-of-the-executing-bash-script
FILESHUB_HOME="`dirname \"$0\"`"                    # relative
FILESHUB_HOME="`( cd \"$FILESHUB_HOME\" && pwd )`"  # absolutized and normalized
if [ -z "$FILESHUB_HOME" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  exit 1  # fail
fi

## -Dfile.encoding=UTF-8
## ISO-8859-1

## ~~HELP~~
## -DFilesHub.hash.frequency: It defines the number of times to spot hash a file when its size is greater than 4 MB.
##                            0 means hash the whole file.

## ~~Requirements~~
##    -To handle path with spaces, you have to double quotes paths.

java -DFilesHub.home="${FILESHUB_HOME}" -Dlogback.configurationFile="${FILESHUB_HOME}/logback.xml" -DFilesHub.hash.frequency=13 -jar "${FILESHUB_HOME}/Fileshub.jar" "$@"
